baseURL = "/"
languageCode = "ru"
theme="mainroad"
paginate = "10"
dateformat = "02-01-2006" # Change the format of dates

# authorbox = true # Show authorbox at bottom of pages if true
defaultContentLanguage="ru" 
# defaultContentLanguageInSubdir = true
# disableLanguages = ["en"]
[languages]
  [languages.ru]
    languageCode = "ru"
    weight = 1 
    title = "Пишем про бизнес-аналитику, данные, кодинг и немного DevOps"
    lang = "ru"
    contentDir = "content/ru"

    [languages.ru.Params.logo]
    image = "img/IDEA-0.png" # Logo image. Path relative to "static"
    title = "Блог IDEA" # Logo title, otherwise will use site title
    subtitle = "Пишем про бизнес-аналитику, данные, кодинг и немного DevOps" # Logo subtitle

    
    [languages.ru.Author] # Used in authorbox
    name = "Максим Девятов"
    url = '/authors/максим-девятов/'
    # permalink = "{{< ref "/author/:author/_index.md" >}}"
    # permalink = "/:title/"
    # bio = "CEO IDEA. Qlik, Python, C++ developer. Certified Servers & Networking Engineer"
#  avatar = "img/avatar.png"

  [languages.ru.menu]
  [[languages.ru.menu.main]]
    identifier = "about"
    name = "Авторы"
    url = "/about"
    weight = -110
  [[languages.ru.menu.main]]
    identifier = "blog"
    name = "Блог"
    url = "/post"
    weight= -150
  [[languages.ru.menu.main]]
    identifier = "contacts"
    name = "Проекты"
    url = "/projects"
    weight = -100




 [languages.en]
    languageCode = "en"
    contentDir = "content/en"
    title = "A blog about business intelligence, data, programming and DevOps"
    weight = 2

    [languages.en.Params.logo]
    image = "img/IDEA-0.png" # Logo image. Path relative to "static"
    title = "IDEA blog" # Logo title, otherwise will use site title
    subtitle = "A blog about business intelligence, data, programming and DevOps" # Logo subtitle

    [languages.en.Author] # Used in authorbox
    name = "Maxim Deviatov"
    bio = "Skills: Qlik, Node.JS, JavaScript, Python, C++. Certified Servers & Networking Engineer"
#  avatar = "img/avatar.png"


  [languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "about"
    name = "Authors"
    url = "/about"
    weight = -110
  [[languages.en.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post"
    weight= -150
  # [[languages.en.menu.main]]
  #   identifier = "projects"
  #   name = "Projects"
  #   url = "/projects"
  #   weight = -100






[Params]
 description = "Blog" # Site description. Used in meta description
  copyright = "Maxim N. Deviatov" # Footer copyright holder, otherwise will use site title
#  opengraph = true # Enable OpenGraph if true
 # schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  # authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02-01-2006" # Change the format of dates
#  mathjax = true # Enable MathJax
#  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
#  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
 # googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
 # googleFontsLink = "https://fonts.googleapis.com/css2?family=Montserrat&display=swap" # Load Google Fonts
 # googleFontsLink = "https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap"
 googleFontsLink = "https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap"
  gtm_id = "GTM-NF6XD6B"
#  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
#  customCSS = ["css/custom.css"] # Include custom CSS files
#<----->  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#1999d0" # Override highlight color
  # highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
 # fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
 # fontFamilyPrimary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  # single = false # Configure layout for single pages
  single = "right"
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]
  # widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget


[Params.widgets.social]
  # Enable parts of social widget
  facebook = "ideabi.ru"
  twitter = "ideacompru"
#  instagram = "username"
#  linkedin = "username"
 telegram = "deviatov"
  github = "mdeviatov"
#  gitlab = "username"
#  bitbucket = "username"
  # email = "bi@ideabi.rd"

# Custom social links
#[[Params.widgets.social.custom]]
  # title = "Youtube"
  # url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

#[[Params.widgets.social.custom]]
#  title = "IDEA Site"
#  url = "https://ideabi.ru"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
